Repository GoogleCloudPlatform/gke-networking-api, pull requests merged in 2024-10, with the labels that each got.

#30 Regenerate CRDs on dependabot PRs.
  .github/workflows/verify-codegen.yaml
Labels: size/M, lgtm, approved

#31 Grant dependabot write permissions on PR events.
  .github/workflows/verify-codegen.yaml
Labels: lgtm, approved, size/XS

#32 Use gke-networking-gh-bot to push commits.
  .github/workflows/verify-codegen.yaml
Labels: lgtm, approved, size/XS

#34 Add release process and changelog.
  CHANGELOG.md
  README.md
  RELEASE.md
Labels: size/M, lgtm, approved

#33 Bump the gomod-dependencies group across 1 directory with 3 updates
  config/crds/networking.gke.io_gcpfirewalls.yaml
  config/crds/networking.gke.io_gkenetworkparamsets.yaml
  config/crds/networking.gke.io_networkinterfaces.yaml
  config/crds/networking.gke.io_networks.yaml
  config/crds/networking.gke.io_nodetopologies.yaml
  go.mod
  go.sum
Labels: size/L, lgtm, approved

#19 Revert "network annotation to hold egress NAT gateway IP"
  CHANGELOG.md
  apis/network/v1/annotations.go
Labels: lgtm, approved, size/XS

#36 Create release v0.2.0.
  CHANGELOG.md
Labels: lgtm, approved, size/XS

#39 Add thebeezee and yswe to OWNERS.
  OWNERS
Labels: lgtm, approved, size/XS

#38 Remove unused v1beta GCP Firewall CRD.
  CHANGELOG.md
  apis/gcpfirewall/v1beta1/BUILD
  apis/gcpfirewall/v1beta1/doc.go
  apis/gcpfirewall/v1beta1/types.go
  apis/gcpfirewall/v1beta1/zz_generated.deepcopy.go
  apis/gcpfirewall/v1beta1/zz_generated.register.go
  client/gcpfirewall/clientset/versioned/clientset.go
  client/gcpfirewall/clientset/versioned/fake/clientset_generated.go
  client/gcpfirewall/clientset/versioned/fake/register.go
  client/gcpfirewall/clientset/versioned/scheme/register.go
  client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/doc.go
  client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/fake/doc.go
  client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/fake/fake_gcpfirewall.go
  client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/fake/fake_gcpfirewall_client.go
  client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/gcpfirewall.go
  client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/gcpfirewall_client.go
  client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/generated_expansion.go
  client/gcpfirewall/informers/externalversions/gcpfirewall/interface.go
  client/gcpfirewall/informers/externalversions/gcpfirewall/v1beta1/gcpfirewall.go
  client/gcpfirewall/informers/externalversions/gcpfirewall/v1beta1/interface.go
  client/gcpfirewall/informers/externalversions/generic.go
  client/gcpfirewall/listers/gcpfirewall/v1beta1/expansion_generated.go
  client/gcpfirewall/listers/gcpfirewall/v1beta1/gcpfirewall.go
  config/crds/networking.gke.io_gcpfirewalls.yaml
  hack/update-codegen.sh
Labels: lgtm, approved, size/XXL

#35 Add subnetwork API with gateway IP
  apis/network/v1/networkinterface_types.go
  apis/network/v1/subnetwork_types.go
  apis/network/v1/zz_generated.deepcopy.go
  apis/network/v1/zz_generated.register.go
  client/network/clientset/versioned/typed/network/v1/fake/fake_network_client.go
  client/network/clientset/versioned/typed/network/v1/fake/fake_subnetwork.go
  client/network/clientset/versioned/typed/network/v1/fake/fake_subnetworklist.go
  client/network/clientset/versioned/typed/network/v1/generated_expansion.go
  client/network/clientset/versioned/typed/network/v1/network_client.go
  client/network/clientset/versioned/typed/network/v1/subnetwork.go
  client/network/clientset/versioned/typed/network/v1/subnetworklist.go
  client/network/informers/externalversions/generic.go
  client/network/informers/externalversions/network/v1/interface.go
  client/network/informers/externalversions/network/v1/subnetwork.go
  client/network/listers/network/v1/expansion_generated.go
  client/network/listers/network/v1/subnetwork.go
  config/crds/networking.gke.io_networkinterfaces.yaml
  config/crds/networking.gke.io_subnetworks.yaml
Labels: lgtm, approved, ok-to-test, size/XL
