Repository GoogleCloudPlatform/gke-networking-api, pull requests merged in 2024-09, with the labels that each got.

#22 Add Node Topology CRD definition.
  apis/nodetopology/v1/BUILD
  apis/nodetopology/v1/doc.go
  apis/nodetopology/v1/types.go
  apis/nodetopology/v1/zz_generated.deepcopy.go
  apis/nodetopology/v1/zz_generated.register.go
  client/nodetopology/clientset/versioned/clientset.go
  client/nodetopology/clientset/versioned/fake/clientset_generated.go
  client/nodetopology/clientset/versioned/fake/doc.go
  client/nodetopology/clientset/versioned/fake/register.go
  client/nodetopology/clientset/versioned/scheme/doc.go
  client/nodetopology/clientset/versioned/scheme/register.go
  client/nodetopology/clientset/versioned/typed/nodetopology/v1/doc.go
  client/nodetopology/clientset/versioned/typed/nodetopology/v1/fake/doc.go
  client/nodetopology/clientset/versioned/typed/nodetopology/v1/fake/fake_nodetopology.go
  client/nodetopology/clientset/versioned/typed/nodetopology/v1/fake/fake_nodetopology_client.go
  client/nodetopology/clientset/versioned/typed/nodetopology/v1/generated_expansion.go
  client/nodetopology/clientset/versioned/typed/nodetopology/v1/nodetopology.go
  client/nodetopology/clientset/versioned/typed/nodetopology/v1/nodetopology_client.go
  client/nodetopology/informers/externalversions/factory.go
  client/nodetopology/informers/externalversions/generic.go
  client/nodetopology/informers/externalversions/internalinterfaces/factory_interfaces.go
  client/nodetopology/informers/externalversions/nodetopology/interface.go
  client/nodetopology/informers/externalversions/nodetopology/v1/interface.go
  client/nodetopology/informers/externalversions/nodetopology/v1/nodetopology.go
  client/nodetopology/listers/nodetopology/v1/expansion_generated.go
  client/nodetopology/listers/nodetopology/v1/nodetopology.go
  config/crds/networking.gke.io_nodetopologies.yaml
  go.mod
  hack/update-codegen.sh
Labels: needs-ok-to-test, lgtm, approved, size/XXL

#25 Bump the gomod-dependencies group across 1 directory with 2 updates
  client/gcpfirewall/clientset/versioned/fake/clientset_generated.go
  client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1/fake/fake_gcpfirewall.go
  client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1/gcpfirewall.go
  client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/fake/fake_gcpfirewall.go
  client/gcpfirewall/clientset/versioned/typed/gcpfirewall/v1beta1/gcpfirewall.go
  client/gcpfirewall/informers/externalversions/factory.go
  client/gcpfirewall/listers/gcpfirewall/v1/gcpfirewall.go
  client/gcpfirewall/listers/gcpfirewall/v1beta1/gcpfirewall.go
  client/network/clientset/versioned/fake/clientset_generated.go
  client/network/clientset/versioned/typed/network/v1/fake/fake_gkenetworkparamset.go
  client/network/clientset/versioned/typed/network/v1/fake/fake_gkenetworkparamsetlist.go
  client/network/clientset/versioned/typed/network/v1/fake/fake_network.go
  client/network/clientset/versioned/typed/network/v1/fake/fake_networkinterface.go
  client/network/clientset/versioned/typed/network/v1/fake/fake_networkinterfacelist.go
  client/network/clientset/versioned/typed/network/v1/fake/fake_networklist.go
  client/network/clientset/versioned/typed/network/v1/gkenetworkparamset.go
  client/network/clientset/versioned/typed/network/v1/gkenetworkparamsetlist.go
  client/network/clientset/versioned/typed/network/v1/network.go
  client/network/clientset/versioned/typed/network/v1/networkinterface.go
  client/network/clientset/versioned/typed/network/v1/networkinterfacelist.go
  client/network/clientset/versioned/typed/network/v1/networklist.go
  client/network/clientset/versioned/typed/network/v1alpha1/fake/fake_gkenetworkparamset.go
  client/network/clientset/versioned/typed/network/v1alpha1/fake/fake_gkenetworkparamsetlist.go
  client/network/clientset/versioned/typed/network/v1alpha1/fake/fake_network.go
  client/network/clientset/versioned/typed/network/v1alpha1/fake/fake_networkinterface.go
  client/network/clientset/versioned/typed/network/v1alpha1/fake/fake_networkinterfacelist.go
  client/network/clientset/versioned/typed/network/v1alpha1/fake/fake_networklist.go
  client/network/clientset/versioned/typed/network/v1alpha1/gkenetworkparamset.go
  client/network/clientset/versioned/typed/network/v1alpha1/gkenetworkparamsetlist.go
  client/network/clientset/versioned/typed/network/v1alpha1/network.go
  client/network/clientset/versioned/typed/network/v1alpha1/networkinterface.go
  client/network/clientset/versioned/typed/network/v1alpha1/networkinterfacelist.go
  client/network/clientset/versioned/typed/network/v1alpha1/networklist.go
  client/network/informers/externalversions/factory.go
  client/network/listers/network/v1/gkenetworkparamset.go
  client/network/listers/network/v1/network.go
  client/network/listers/network/v1/networkinterface.go
  client/network/listers/network/v1alpha1/gkenetworkparamset.go
  client/network/listers/network/v1alpha1/network.go
  client/network/listers/network/v1alpha1/networkinterface.go
  client/nodetopology/clientset/versioned/fake/clientset_generated.go
  client/nodetopology/clientset/versioned/typed/nodetopology/v1/fake/fake_nodetopology.go
  client/nodetopology/clientset/versioned/typed/nodetopology/v1/nodetopology.go
  client/nodetopology/informers/externalversions/factory.go
  client/nodetopology/listers/nodetopology/v1/nodetopology.go
  hack/go.mod
  hack/go.sum
Labels: lgtm, approved, size/XXL

#26 Adds 'description' field to GCPFirewall CRD and corresponding api
  apis/gcpfirewall/v1/types.go
  config/crds/networking.gke.io_gcpfirewalls.yaml
Labels: needs-ok-to-test, lgtm, approved, size/S
